### ISSUE TITLE
incorrect CIGAR

### ISSUE THREAD

**Issue by selkovjr** [ding-lab/Pindel2BAM#1]
Given this input:

```
####################################################################################################
31      D 9     NT 9 "TTTTTTTTT"        ChrID 5 BP 68565044     68565054        BP_range 68565044       68565054        Supports 17     17      + 0     0       - 17    17      S1 18   SUM_MS 1190     2       NumSupSamples 2 2       Normal 370 402 0 0 4 4  Tumor 187 209 0 0 13 13
ATTGCATCACTCACTGCAGCCTGGGTGACAGAGCGAGACTCTGTCTCTCTAAAAAAAGAAAAAAATTAAAAAAAAAAAACCCACCTTGAAAAGTCTCCCTCTTACTTTCTTTCAGGTTCCTTTTTT         TTCAGACCTTGATCAGCTAACAAGAATATTTGAAACTTTGGGCACACCAACTGAGGAACAGTGGCCGGTAAGCCTTTATGCATTTTCTTTGAAATGTAATTAGGACTCTGTAAAGTTCTTAAACTG
                                                                          AAAAACCCACCTTGAAAAGTCTCCCTCTTACTTTCTTTCAGGTTCCTTTTTTTTTTTTTGTTTCAGACCTTGATCAGCTAACAAGAATATTTGAAACTTTGGGCACACCAACTGAGGAACAGTGGC                -       68565142        70      Tumor   @K00346:24:HFKG7BBXX:3:2110:8633:41563/2
```

`pin2sam` generates the following SAM record:
```
K00346:24:HFKG7BBXX:3:2110:8633:41563	18	5	68564993	60	52M9I9D65M	*	0	0	AAAAACCCACCTTGAAAAGTCTCCCTCTTACTTTCTTTCAGGTTCCTTTTTTTTTTTTTGTTTCAGACCTTGATCAGCTAACAAGAATATTTGAAACTTTGGGCACACCAACTGAGGAACAGTGGC	*	PG:Z:Pindel,CI:Z:52M9I9D65M
```

This alignment does not contain a deletion. However, the generated CIGAR tag includes `9D`.

**Comment by AdamDS** [comment]
@selkovjr 
It looks as though your input shows a 9bp deletion and 9bp insertion. There are two things I see with your input that suggests to me that the generated CIGAR string is correct.
1) In the pindel information line, there is a "D 9", suggesting that a 9bp deletion was found along with a 9bp insertion, "NT 9".
2) The first sample has in the middle of its string, "CTTTTTT         TTCAG", and there are 9 spaces as the gap.
The output will not have a gap, as per standards of the [.sam/.bam format description](https://samtools.github.io/hts-specs/SAMv1.pdf), for example "r001 99 ref 7 30 14M1D3M = 39 41 TTAGATAAAGGATACTG *".
Maybe I am not catching what you're suggesting. What aspects of input/output suggest to you that there should not be a 9bp deletion?

**Comment by selkovjr** [comment]
Adam,

Thank you for looking into it. Now I have seen more examples, and they are all like that. It must be some sort of sequencing error. Properly aligned, it looks like this:

```
ref:   TTCCTTTTTT---------gccaggagaTTCAGA
query: TTCCTTTTTTTTTTTTTTT---------TTCAGA
```
and there is no limit to how long these features can be. I have seen 80-mer Ts overriding 80-base long sequences; that's not just stutter, it looks like template-free polymerization getting out of hand. I couldn't believe that was possible, and pindel alignments looked confusing until I realized that not everything on the reference line was reference.

Walking away in bewilderment...
